import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getCurrentUserProfile } from '@/lib/auth'
import { createServiceRoleClient } from '@/lib/supabase/admin'

/**
 * Get contracts for an organization
 * GET /api/contracts?orgId=xxx
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const orgId = searchParams.get('orgId')

    if (!orgId) {
      return NextResponse.json({ error: 'orgId is required' }, { status: 400 })
    }

    // Check permissions
    const profile = await getCurrentUserProfile()
    const isAdmin = profile?.is_platform_admin || false

    if (!isAdmin) {
      // Check if user is org admin for this org
      const { data: membership } = await supabase
        .from('org_memberships')
        .select('role')
        .eq('org_id', orgId)
        .eq('user_id', user.id)
        .single()

      if (!membership || membership.role !== 'org_admin') {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 403 })
      }
    }

    const { data, error } = await supabase
      .from('contracts')
      .select('*')
      .eq('org_id', orgId)
      .order('created_at', { ascending: false })

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json(data || [])
  } catch (error: any) {
    console.error('Contracts fetch error:', error)
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 })
  }
}

/**
 * Create a new contract
 * POST /api/contracts
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { org_id, name, description, start_date, end_date, contract_value, terms, status } = body

    if (!org_id || !name || !start_date) {
      return NextResponse.json({ error: 'org_id, name, and start_date are required' }, { status: 400 })
    }

    // Check permissions
    const profile = await getCurrentUserProfile()
    const isAdmin = profile?.is_platform_admin || false

    if (!isAdmin) {
      // Check if user is org admin for this org
      const { data: membership } = await supabase
        .from('org_memberships')
        .select('role')
        .eq('org_id', org_id)
        .eq('user_id', user.id)
        .single()

      if (!membership || membership.role !== 'org_admin') {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 403 })
      }
    }

    const adminSupabase = createServiceRoleClient()

    // Contract number will be auto-generated by trigger if not provided
    const { data, error } = await adminSupabase
      .from('contracts')
      .insert({
        org_id,
        name,
        description: description || null,
        start_date,
        end_date: end_date || null,
        contract_value: contract_value || null,
        terms: terms || null,
        status: status || 'active',
        contract_number: body.contract_number || null // Will be auto-generated if null
      })
      .select()
      .single()

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json(data)
  } catch (error: any) {
    console.error('Contract creation error:', error)
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 })
  }
}
